{% set name = "py-solc-x" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py-solc-x-{{ version }}.tar.gz
  sha256: e825b1d7178c0811b95a685e37604df0afda2689ff9ecf14a625df03ea11e64a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - setuptools-markdown
  run:
    - python >=3.6,<4.0
    - requests >=2.19.0,<3
    - semantic_version >=2.8.1,<3

test:
  imports:
    - solcx
    - solcx.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iamdefinitelyahuman/py-solc-x
  summary: Python wrapper and version management tool for the solc Solidity compiler.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
