{% set name = "py-solc-x" %}
{% set version = "2.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d8440d2be8a5577137fb2313ee211b5b35f36c4c922f274192d34f401616e83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-markdown
  run:
    - python >={{ python_min }},<4.0
    - requests >=2.19.0,<3
    - packaging >=23.1

test:
  imports:
    - solcx
    - solcx.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iamdefinitelyahuman/py-solc-x
  summary: Python wrapper and version management tool for the solc Solidity compiler.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
