{% set name = "py-solc-x" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py-solc-x-{{ version }}.tar.gz
  sha256: 6f6f7f47c8520bde73679624568ec343db9baca6914212b371896fad8697deca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-markdown
  run:
    - python >={{ python_min }},<4.0
    - requests >=2.19.0,<3
    - packaging >=23.1,<24

test:
  imports:
    - solcx
    - solcx.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iamdefinitelyahuman/py-solc-x
  summary: Python wrapper and version management tool for the solc Solidity compiler.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
